services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: intern_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"