spring.application.name=virality-engine

# PostgreSQL Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/intern_db?options=-c%20timezone=UTC
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
